




CREATE OR REPLACE PROCEDURE spipx024k15r04 ( l_inUserId SUSER.USER_ID%TYPE,                 -- ユーザーID
 l_inItakuKaishaCd MITAKU_KAISHA.ITAKU_KAISHA_CD%TYPE, -- 委託会社コード
 l_inKijunYmdFrom KIKIN_SEIKYU.SHR_YMD%TYPE,          -- 基準日
 l_inChohyoKbn text,                            -- 帳票区分
 l_inGyomuYmd TEXT,                               -- 業務日付
 l_outSqlCode OUT integer,                            -- リターン値
 l_outSqlErrM OUT text                           -- エラーコメント
 ) AS $body$
DECLARE

--
-- * 著作権: Copyright (c) 2017
-- * 会社名: JIP
-- *
-- * 元利金支払における勘定起票の確認をするための帳票データを作成する。
-- *
-- * @author Y.Yamada
-- * @version $Id: SPIPX024K15R04.sql,v 1.0 2017/01/05 13:10:20 Y.Yamada Exp $
-- *
-- * @param l_inUserId	    IN SUSER.USER_ID%TYPE				  ユーザーID
-- * @param l_inItakuKaishaCd IN MITAKU_KAISHA.ITAKU_KAISHA_CD%TYPE 委託会社コード
-- * @param l_inKijunYmdFrom  IN KIKIN_SEIKYU.SHR_YMD%TYP 基準日
-- * @param l_inChohyoKbn     IN VARCHAR 帳票区分
-- * @param l_inGyomuYmd	    IN TEXT 業務日付
-- * @param l_outSqlCode	    OUT NUMERIC リターン値
-- * @param l_outSqlErrM	    OUT VARCHAR エラーコメント
-- *
-- * @return なし
-- 
--==============================================================================
--                定数定義                                                      
--==============================================================================
	C_PROCEDURE_ID  CONSTANT text := 'SPIPX024K15R04';	-- プロシージャＩＤ
	C_REPORT_ID     CONSTANT text := 'IP931502931';		-- 勘定起票明細表
	-- 勘定区分
	C_KNJKBN_DAIKO				CONSTANT text := '02';	-- 決済代行
	C_KNJKBN_CUSTODY			CONSTANT text := '03';	-- カストディ
	C_KNJKBN_KABU				CONSTANT text := '04';	-- 株式クリアリング
	C_KNJKBN_HOYU				CONSTANT text := '05';	-- 自行 保有分
	C_KNJKBN_MADOHAN			CONSTANT text := '06';	-- 自行 窓販分
	C_KNJKBN_SHINTAKU			CONSTANT text := '07';	-- 自行 信託口
--==============================================================================
--                変数定義                                                      
--==============================================================================
	v_item type_sreport_wk_item;						-- Composite type for pkPrint.insertData
	gSeqNo		integer := 0;				-- カウンター
	gRtnCd 		integer := pkconstant.success(); 		-- リターンコード
	gItakuKaishaRnm SOWN_INFO.BANK_RNM%TYPE;                        -- 委託会社略名
	gSKN_KESSAI_Rnm varchar(100) := NULL;                     -- 資金決済会社略称
	gERRCOUNT_MGR   integer;
	gERRCOUNT_KIKIN integer;
	gJikoDaikoKbn	SOWN_INFO.JIKO_DAIKO_KBN%TYPE;
	gTSUKA_FORMAT		varchar(21) := NULL;		-- 通貨フォーマット
--==============================================================================
--                    カーソル定義                                              
--==============================================================================
	curMeisai CURSOR FOR
	SELECT
		MAIN_K01.ITAKU_KAISHA_CD AS ITAKU_KAISHA_CD, --委託会社コード
		MAIN_K01.SKN_KESSAI_CD, --資金決済会社コード
		MAIN_K01.SHR_YMD, --勘定日
		MAIN_K01.TSUKA_CD, --通貨コード
		M64.TSUKA_NM, --通貨出力用名称
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK01, 0)) AS SHOKAN_SEIKYU_KNGK01,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK01, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK01,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK02, 0)) AS SHOKAN_SEIKYU_KNGK02,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK02, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK02,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK03, 0)) AS SHOKAN_SEIKYU_KNGK03,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK03, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK03,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK04, 0)) AS SHOKAN_SEIKYU_KNGK04,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK04, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK04,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK05, 0)) AS SHOKAN_SEIKYU_KNGK05,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK05, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK05,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK06, 0)) AS SHOKAN_SEIKYU_KNGK06,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK06, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK06,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK07, 0)) AS SHOKAN_SEIKYU_KNGK07,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK07, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK07,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK08, 0)) AS SHOKAN_SEIKYU_KNGK08,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK08, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK08,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK09, 0)) AS SHOKAN_SEIKYU_KNGK09,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK09, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK09,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK10, 0)) AS SHOKAN_SEIKYU_KNGK10,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK10, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK10,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK11, 0)) AS SHOKAN_SEIKYU_KNGK11,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK11, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK11,
		SUM(coalesce(MAIN_K01.SHOKAN_SEIKYU_KNGK12, 0)) AS SHOKAN_SEIKYU_KNGK12,
		SUM(coalesce(MAIN_K01.GZEIHIKI_AFT_CHOKYU_KNGK12, 0)) AS GZEIHIKI_AFT_CHOKYU_KNGK12,
		SUM(K02.KKN_NYUKIN_KNGK) AS KKN_NYUKIN_KNGK,
		SUM(MAIN_K01.GZEIHIKI_BEF_CHOKYU_KNGK) AS GZEIHIKI_BEF_CHOKYU_KNGK
	FROM mtsuka m64, (
			SELECT
				SUB_K01.ITAKU_KAISHA_CD	AS   ITAKU_KAISHA_CD,	--委託会社コード
				SUB_K01.SKN_KESSAI_CD  AS SKN_KESSAI_CD,	--資金決済会社コード
				SUB_K01.SHR_YMD	AS   SHR_YMD,	--勘定日
				SUB_K01.TSUKA_CD AS	TSUKA_CD,  --通貨コード
				SUB_K01.MGR_CD   AS  MGR_CD,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK01,  0))  AS SHOKAN_SEIKYU_KNGK01,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK01,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK01,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK02,  0))  AS SHOKAN_SEIKYU_KNGK02,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK02,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK02,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK03,  0))  AS SHOKAN_SEIKYU_KNGK03,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK03,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK03,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK04,  0))  AS SHOKAN_SEIKYU_KNGK04,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK04,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK04,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK05,  0))  AS SHOKAN_SEIKYU_KNGK05,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK05,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK05,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK06,  0))  AS SHOKAN_SEIKYU_KNGK06,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK06,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK06,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK07,  0))  AS SHOKAN_SEIKYU_KNGK07,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK07,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK07,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK08,  0))  AS SHOKAN_SEIKYU_KNGK08,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK08,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK08,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK09,  0))  AS SHOKAN_SEIKYU_KNGK09,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK09,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK09,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK10,  0))  AS SHOKAN_SEIKYU_KNGK10,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK10,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK10,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK11,  0))  AS SHOKAN_SEIKYU_KNGK11,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK11,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK11,
				SUM(coalesce(SUB_K01.SHOKAN_SEIKYU_KNGK12,  0))  AS SHOKAN_SEIKYU_KNGK12,
				SUM(coalesce(SUB_K01.GZEIHIKI_AFT_CHOKYU_KNGK12,	0))	AS   GZEIHIKI_AFT_CHOKYU_KNGK12,
				SUM(SUB_K01.GZEIHIKI_BEF_CHOKYU_KNGK)  AS GZEIHIKI_BEF_CHOKYU_KNGK
			FROM (
					--==============================================================
					--	SB・CB	日銀当預決済
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK01,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK01,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK    --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD <> VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    )
UNION ALL

					--==============================================================
					--	SB	決済代行
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK02,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK02,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_DAIKO
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')          
UNION ALL

					--==============================================================
					--	SB	カストディ
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK03,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK03,   --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_CUSTODY
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')          
UNION ALL

					--==============================================================
					--	CB	カストディ
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK03,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK03,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_CUSTODY
							AND BT33.SHASAI_KBN = 'CB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI IN ('80','89')          
UNION ALL

					--==============================================================
					--	CB	株式クリアリング
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK04,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK04,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_KABU
							AND BT33.SHASAI_KBN = 'CB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI IN ('80','89')          
UNION ALL

					--==============================================================
					--	SB	自行　保有分
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK05,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK05,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_HOYU
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')          
UNION ALL

					--==============================================================
					--	SB	自行　窓販分
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK06,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK06,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_MADOHAN
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')          
UNION ALL

					--==============================================================
					--	SB	自行　信託分
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK07,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK07,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_SHINTAKU
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')          
UNION ALL

					--==============================================================
					--	SB	その他　機構加入者コードが他行
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK08,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK08,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD <> '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')          
UNION ALL

					--==============================================================
					--	CB	その他　機構加入者コードが他行
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK08,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK08,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD <> '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND VMG1.SAIKEN_SHURUI IN ('80','89')          
UNION ALL

					--==============================================================
					--	SB	その他　機構加入者コードが自行・口座区分がその他
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK08,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK08,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN NOT IN (		-- 勘定内訳管理マスタ（SB）に振り分け登録されていない口座区分
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')          
UNION ALL

					--==============================================================
					--	CB	その他　機構加入者コードが自行・口座区分がその他
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK08,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK08,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK   --2017/10/2 upd by matsuda
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN NOT IN (		-- 勘定内訳管理マスタ（CB）に振り分け登録されていない口座区分
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.SHASAI_KBN = 'CB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI IN ('80','89')          
UNION ALL

					--==============================================================
					--	SB	決済代行（関与）
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK09,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK09,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						0 AS GZEIHIKI_BEF_CHOKYU_KNGK
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_DAIKO
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89') AND VMG1.KK_KANYO_FLG = '1'          
UNION ALL

					--==============================================================
					--	SB	決済代行（非関与）
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK10,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK10,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						0 AS GZEIHIKI_BEF_CHOKYU_KNGK
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_DAIKO
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89') AND VMG1.KK_KANYO_FLG = '0'          
UNION ALL

					--==============================================================
					--	SB	決済代行（実質記番号）
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK11,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK11,  --2017/10/2 upd by matsuda
						NULL::numeric AS SHOKAN_SEIKYU_KNGK12,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK12,
						0 AS GZEIHIKI_BEF_CHOKYU_KNGK
					FROM mgr_kihon_view vmg1, kikin_seikyu k01
LEFT OUTER JOIN kikin_seikyu2 bt12 ON (K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD AND K01.MGR_CD = BT12.MGR_CD AND K01.SHR_YMD = BT12.SHR_YMD AND K01.TSUKA_CD = BT12.TSUKA_CD AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN AND K01.BANK_CD = BT12.BANK_CD AND K01.KOZA_KBN = BT12.KOZA_KBN AND K01.TAX_KBN = BT12.TAX_KBN)
WHERE K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD AND K01.SHR_YMD = l_inKijunYmdFrom AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd AND K01.AITE_SKN_KESSAI_BCD || K01.AITE_SKN_KESSAI_SCD = VMG1.SKN_KESSAI_CD AND K01.MGR_CD = VMG1.MGR_CD AND K01.FINANCIAL_SECURITIES_KBN || K01.BANK_CD = '0' || pkconfiguration.kaiinid() AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1'
							AND BT12.KNJ_FLG <> '1')
						    ) AND K01.KOZA_KBN IN (
							SELECT BT33.KOZA_KBN
							FROM KANJO_KANRI BT33
							WHERE BT33.KANJO_KBN = C_KNJKBN_DAIKO
							AND BT33.SHASAI_KBN = 'SB'
							AND l_inKijunYmdFrom BETWEEN BT33.TEKIYOST_YMD AND coalesce(trim(both BT33.TEKIYOED_YMD), '99999999') 
						) AND VMG1.SAIKEN_SHURUI NOT IN ('80','89') AND VMG1.KK_KANYO_FLG = '2'          
UNION ALL

					--==============================================================
					--	SB	勘定処理対象外
					--==============================================================
					SELECT
						K01.ITAKU_KAISHA_CD,
						VMG1.SKN_KESSAI_CD,
						K01.SHR_YMD,
						K01.TSUKA_CD,
						K01.MGR_CD,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK01,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK01,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK02,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK02,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK03,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK03,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK04,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK04,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK05,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK05,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK06,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK06,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK07,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK07,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK08,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK08,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK09,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK09,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK10,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK10,
						NULL::numeric AS SHOKAN_SEIKYU_KNGK11,
						NULL::numeric AS GZEIHIKI_AFT_CHOKYU_KNGK11,
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.SHOKAN_SEIKYU_KNGK  ELSE BT12.SHOKAN_SEIKYU_KNGK END  AS SHOKAN_SEIKYU_KNGK12,                    --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_AFT_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_AFT_CHOKYU_KNGK END  AS GZEIHIKI_AFT_CHOKYU_KNGK12,  --2017/10/2 upd by matsuda
						CASE WHEN K01.KK_KANYO_UMU_FLG='1' THEN K01.GZEIHIKI_BEF_CHOKYU_KNGK  ELSE BT12.GZEIHIKI_BEF_CHOKYU_KNGK END  AS GZEIHIKI_BEF_CHOKYU_KNGK     --2017/10/2 upd by matsuda
					FROM
						KIKIN_SEIKYU K01,
						MGR_KIHON_VIEW VMG1,
						KIKIN_SEIKYU2 BT12
					WHERE
						    K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD
						AND K01.SHR_YMD = l_inKijunYmdFrom
						AND K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd
						AND K01.MGR_CD = VMG1.MGR_CD
						AND (K01.KK_KANYO_UMU_FLG = '1'
							OR (K01.KK_KANYO_UMU_FLG != '1'
							AND K01.SHORI_KBN = '1')
						    )
						AND VMG1.SAIKEN_SHURUI NOT IN ('80','89')
						AND K01.ITAKU_KAISHA_CD = BT12.ITAKU_KAISHA_CD
						AND K01.MGR_CD = BT12.MGR_CD
						AND K01.SHR_YMD = BT12.SHR_YMD
						AND K01.TSUKA_CD = BT12.TSUKA_CD
						AND K01.FINANCIAL_SECURITIES_KBN = BT12.FINANCIAL_SECURITIES_KBN
						AND K01.BANK_CD = BT12.BANK_CD
						AND K01.KOZA_KBN = BT12.KOZA_KBN
						AND K01.TAX_KBN = BT12.TAX_KBN
						AND BT12.KNJ_FLG = '1' 
				) SUB_K01 
			GROUP BY
				SUB_K01.ITAKU_KAISHA_CD, --委託会社コード
				SUB_K01.SKN_KESSAI_CD, --資金決済会社コード
				SUB_K01.SHR_YMD, --勘定日
				SUB_K01.TSUKA_CD, --通貨コード,
				SUB_K01.MGR_CD
		) main_k01
LEFT OUTER JOIN kikin_ido k02 ON (MAIN_K01.ITAKU_KAISHA_CD = K02.ITAKU_KAISHA_CD AND MAIN_K01.MGR_CD = K02.MGR_CD AND MAIN_K01.TSUKA_CD = K02.TSUKA_CD AND MAIN_K01.SHR_YMD = K02.RBR_YMD AND '21' = K02.KKN_IDO_KBN AND '1' >= K02.DATA_SAKUSEI_KBN)
WHERE MAIN_K01.TSUKA_CD = M64.TSUKA_CD      -- 入金（利払）
  -- 請求書出力済
 GROUP BY
		MAIN_K01.ITAKU_KAISHA_CD, --委託会社コード
		MAIN_K01.SKN_KESSAI_CD, --資金決済会社コード
		MAIN_K01.SHR_YMD, --勘定日
		MAIN_K01.TSUKA_CD, --通貨コード
		M64.TSUKA_NM  --通貨出力用名称
	ORDER BY
		MAIN_K01.ITAKU_KAISHA_CD, --委託会社コード
		MAIN_K01.SKN_KESSAI_CD, --資金決済会社コード
		MAIN_K01.SHR_YMD, --勘定日
		MAIN_K01.TSUKA_CD; --通貨コード
--==============================================================================
--                メイン処理                                                       
--==============================================================================
BEGIN
	-- 入力パラメータのチェック
	IF coalesce(trim(both l_inItakuKaishaCd)::text, '') = '' OR coalesce(trim(both l_inKijunYmdFrom)::text, '') = '' OR coalesce(trim(both l_inUserId)::text, '') = '' OR
	   coalesce(trim(both l_inGyomuYmd)::text, '') = '' OR coalesce(trim(both l_inChohyoKbn)::text, '') = ''  THEN
		-- パラメータエラー
		CALL pkLog.fatal('ECM701', C_PROCEDURE_ID, 'パラメータエラー');
		l_outSqlCode := pkconstant.FATAL();
		l_outSqlErrM := '';
		RETURN;
	END IF;
	-- 該当する銘柄が未承認の場合、エラー（エラーコード：４）
	SELECT
		COUNT(VMG1.ITAKU_KAISHA_CD)
	INTO STRICT
		gERRCOUNT_MGR
	FROM
		MGR_KIHON_VIEW VMG1,
		KIKIN_SEIKYU K01
	WHERE
		K01.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD
		AND K01.MGR_CD = VMG1.MGR_CD
                AND VMG1.ITAKU_KAISHA_CD = l_inItakuKaishaCd
                AND K01.SHR_YMD = l_inKijunYmdFrom
		AND VMG1.MGR_STAT_KBN = '0';
	IF gERRCOUNT_MGR > 0 THEN
		-- エラー
		l_outSqlCode := 4;
		l_outSqlErrM := '';
		RETURN;
	END IF;
	-- 元利金請求明細（非関与）が未承認の場合、エラー（エラーコード：３）
	SELECT
		COUNT(K01.ITAKU_KAISHA_CD)
	INTO STRICT
		gERRCOUNT_KIKIN
	FROM
		KIKIN_SEIKYU K01
	WHERE
                K01.ITAKU_KAISHA_CD = l_inItakuKaishaCd
                AND K01.SHR_YMD = l_inKijunYmdFrom
		AND (K01.KK_KANYO_UMU_FLG = '0'
			AND K01.SHORI_KBN ='0');
	IF gERRCOUNT_KIKIN > 0 THEN
		-- エラー
		l_outSqlCode := 3;
		l_outSqlErrM := '';
		RETURN;
	END IF;
	-- 帳票ワークの削除
	DELETE FROM SREPORT_WK
		WHERE KEY_CD = l_inItakuKaishaCd
		AND USER_ID = l_inUserId
		AND CHOHYO_KBN = l_inChohyoKbn
		AND SAKUSEI_YMD = l_inGyomuYmd
		AND CHOHYO_ID = C_REPORT_ID;
	-- ヘッダレコードを追加
	CALL pkPrint.insertHeader(l_inItakuKaishaCd,
			     l_inUserId,
			     l_inChohyoKbn,
			     l_inGyomuYmd,
			     C_REPORT_ID);
	-- 自行代行区分、委託会社略称取得
    BEGIN
	    SELECT
    		JIKO_DAIKO_KBN,
    		CASE WHEN JIKO_DAIKO_KBN='2' THEN  BANK_RNM  ELSE ' ' END
	    INTO STRICT
    		gJikoDaikoKbn,
    		gItakuKaishaRnm
	    FROM
    		VJIKO_ITAKU
	    WHERE
    		KAIIN_ID = l_inItakuKaishaCd;
    EXCEPTION
	    WHEN no_data_found THEN
             gJikoDaikoKbn :=  '1';
             gItakuKaishaRnm := ' ';
    END;
	-- データ登録処理
	FOR recMeisai IN curMeisai LOOP
		-- シーケンスナンバーをカウントアップしておく
		gSeqNo := gSeqNo + 1;
    	IF gJikoDaikoKbn = '1' THEN
    		gSKN_KESSAI_Rnm := ' ';
    	ELSE
    		gSKN_KESSAI_Rnm := pkIpaName.getSknKessaiRnm(recMeisai.ITAKU_KAISHA_CD,recMeisai.SKN_KESSAI_CD);
    	END IF;
    	-- 書式フォーマット、通貨コードの設定
    	IF recMeisai.TSUKA_CD = 'JPY' THEN
    		gTSUKA_FORMAT := 'ZZ,ZZZ,ZZZ,ZZZ,ZZ9';
    	ELSE
    		gTSUKA_FORMAT := 'ZZ,ZZZ,ZZZ,ZZZ,ZZ9.99';
    	END IF;
		-- 帳票ワークへデータを追加
				-- Clear composite type
		v_item := ROW();
		
		v_item.l_inItem001 := gItakuKaishaRnm;	-- 委託会社略称
		v_item.l_inItem002 := gSKN_KESSAI_Rnm;	-- 資金決済会社略称
		v_item.l_inItem003 := recMeisai.ITAKU_KAISHA_CD;	-- 委託会社コード
		v_item.l_inItem004 := recMeisai.SKN_KESSAI_CD;	-- 資金決済会社コード
		v_item.l_inItem005 := recMeisai.TSUKA_CD;	-- 通貨コード
		v_item.l_inItem006 := recMeisai.SHR_YMD;	-- 勘定日
		v_item.l_inItem007 := recMeisai.TSUKA_NM;	-- 発行通貨
		v_item.l_inItem008 := gTSUKA_FORMAT;
		v_item.l_inItem009 := recMeisai.SHOKAN_SEIKYU_KNGK01;
		v_item.l_inItem010 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK01;
		v_item.l_inItem011 := recMeisai.SHOKAN_SEIKYU_KNGK02;
		v_item.l_inItem012 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK02;
		v_item.l_inItem013 := recMeisai.SHOKAN_SEIKYU_KNGK03;
		v_item.l_inItem014 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK03;
		v_item.l_inItem015 := recMeisai.SHOKAN_SEIKYU_KNGK04;
		v_item.l_inItem016 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK04;
		v_item.l_inItem017 := recMeisai.SHOKAN_SEIKYU_KNGK05;
		v_item.l_inItem018 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK05;
		v_item.l_inItem019 := recMeisai.SHOKAN_SEIKYU_KNGK06;
		v_item.l_inItem020 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK06;
		v_item.l_inItem021 := recMeisai.SHOKAN_SEIKYU_KNGK07;
		v_item.l_inItem022 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK07;
		v_item.l_inItem023 := recMeisai.SHOKAN_SEIKYU_KNGK08;
		v_item.l_inItem024 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK08;
		v_item.l_inItem025 := recMeisai.KKN_NYUKIN_KNGK;
		v_item.l_inItem026 := recMeisai.SHOKAN_SEIKYU_KNGK09;
		v_item.l_inItem027 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK09;
		v_item.l_inItem028 := recMeisai.SHOKAN_SEIKYU_KNGK10;
		v_item.l_inItem029 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK10;
		v_item.l_inItem030 := recMeisai.SHOKAN_SEIKYU_KNGK11;
		v_item.l_inItem031 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK11;
		v_item.l_inItem032 := recMeisai.SHOKAN_SEIKYU_KNGK12;
		v_item.l_inItem033 := recMeisai.GZEIHIKI_AFT_CHOKYU_KNGK12;
		v_item.l_inItem034 := C_REPORT_ID;	-- 帳票ID
		v_item.l_inItem035 := l_inUserId;	-- ユーザーID
		
		-- Call pkPrint.insertData with composite type
		CALL pkPrint.insertData(
			l_inKeyCd		=> l_inItakuKaishaCd,
			l_inUserId		=> l_inUserId,
			l_inChohyoKbn	=> l_inChohyoKbn,
			l_inSakuseiYmd	=> l_inGyomuYmd,
			l_inChohyoId	=> C_REPORT_ID,
			l_inSeqNo		=> gSeqNo,
			l_inHeaderFlg	=> '1',
			l_inItem		=> v_item,
			l_inKousinId	=> l_inUserId,
			l_inSakuseiId	=> l_inUserId
		);
	-- レコード数分ループの終了
	END LOOP;
	-- 「対象データなし」レコード登録
	IF gSeqNo = 0 THEN
		-- リターンコードのセット
		gRtnCd := pkconstant.NO_DATA_FIND();
		-- 帳票ワークへデータを追加
				-- Clear composite type
		v_item := ROW();
		
		v_item.l_inItem001 := '対象データなし';
		v_item.l_inItem006 := l_inKijunYmdFrom;	-- 勘定日
		v_item.l_inItem034 := C_REPORT_ID;	-- 帳票ID
		v_item.l_inItem035 := l_inUserId;	-- ユーザーID
		
		-- Call pkPrint.insertData with composite type
		CALL pkPrint.insertData(
			l_inKeyCd		=> l_inItakuKaishaCd,
			l_inUserId		=> l_inUserId,
			l_inChohyoKbn	=> l_inChohyoKbn,
			l_inSakuseiYmd	=> l_inGyomuYmd,
			l_inChohyoId	=> C_REPORT_ID,
			l_inSeqNo		=> 1,
			l_inHeaderFlg	=> '1',
			l_inItem		=> v_item,
			l_inKousinId	=> l_inUserId,
			l_inSakuseiId	=> l_inUserId
		);
	END IF;
	-- 終了処理
	l_outSqlCode := gRtnCd;
	l_outSqlErrM := '';
  -- エラー処理
EXCEPTION
	WHEN OTHERS THEN
		CALL pkLog.fatal('ECM701', C_REPORT_ID, 'SQLCODE:' || SQLSTATE);
		CALL pkLog.fatal('ECM701', C_REPORT_ID, 'SQLERRM:' || SQLERRM);
		l_outSqlCode := pkconstant.FATAL();
		l_outSqlErrM := SQLERRM;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE spipx024k15r04 ( l_inUserId SUSER.USER_ID%TYPE, l_inItakuKaishaCd MITAKU_KAISHA.ITAKU_KAISHA_CD%TYPE, l_inKijunYmdFrom KIKIN_SEIKYU.SHR_YMD%TYPE, l_inChohyoKbn text, l_inGyomuYmd TEXT, l_outSqlCode OUT numeric, l_outSqlErrM OUT text ) FROM PUBLIC;