#!/bin/bash
# This script replaces the second insertData call in hyms-2185.SPIPX020K00R01.sql

sed -i '591,606d' hyms-2185.SPIPX020K00R01.sql

sed -i '590a\-- 明細レコード追加（対象データなし）\
v_item := ROW(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)::TYPE_SREPORT_WK_ITEM;\
v_item.l_inItem001 := l_inUserId;\
v_item.l_inItem003 := gItakuKaishaRnm;\
v_item.l_inItem097 := C_CHOHYO_ID;\
v_item.l_inItem098 := '\''対象データなし'\'';\
\
CALL pkPrint.insertData(\
KeyCd      => l_inItakuKaishaCd, -- 識別コード\
UserId     => l_inUserId,        -- ユーザＩＤ\
ChohyoKbn  => l_inChohyoKbn,     -- 帳票区分\
SakuseiYmd => l_inGyomuYmd,      -- 作成日付\
ChohyoId   => C_CHOHYO_ID,       -- 帳票ＩＤ\
SeqNo      => 1,                 -- 連番\
HeaderFlg  => '\''1'\'',         -- ヘッダフラグ\
Item       => v_item,            -- 項目\
KousinId   => l_inUserId,        -- 更新者\
SakuseiId  => l_inUserId         -- 作成者\
);' hyms-2185.SPIPX020K00R01.sql

echo "Second insertData call converted"
