-- Migration script for SCOMPARING_CONDITION table
-- Converted Oracle outer join syntax (+) to PostgreSQL LEFT JOIN
-- Generated by nzha-3064.convert_scomparing.py

-- Clear existing data
TRUNCATE TABLE scomparing_condition;

-- Record: R0411
-- NOTE: Converted Oracle outer join (+) to LEFT OUTER JOIN
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411',
    'VMG1.MGR_CD, VMG1.MGR_RNM, RT02R.ITEM005, RT02R.ITEM006, RT02R.ITEM009, RT02R.ITEM016, RT02R.ITEM021, RT02R.ITEM025, RT02R.ITEM029, RT02R.ITEM038, RT02R.SOUJU_METHOD_CD, RT02S.DENBUN_MEISAI_NO',
    'KK_RENKEI RT02R, MGR_KIHON_VIEW VMG1
    LEFT OUTER JOIN KK_RENKEI RT02S ON (RT02S.JIP_DENBUN_CD = ''S0511'' 
        AND pkIpaName.getBicNoShitenCd(RT02R.SR_BIC_CD) = pkIpaName.getBicNoShitenCd(RT02S.SR_BIC_CD) 
        AND RT02R.ITEM005 = RT02S.ITEM005)',
    'RT02R.ITEM005 = VMG1.ISIN_CD',
    'RT02S.KK_SAKUSEI_DT DESC',
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0411_01
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411_01',
    NULL,
    'MGR_KIHON_VIEW VMG1, KK_RENKEI RT02R',
    'RT02R.ITEM005 = VMG1.ISIN_CD',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0411_02
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411_02',
    NULL,
    'MGR_KIHON_VIEW VMG1, MGR_RBRKIJ MG2, KK_RENKEI RT02R',
    'RT02R.ITEM005 = VMG1.ISIN_CD AND VMG1.ITAKU_KAISHA_CD = MG2.ITAKU_KAISHA_CD AND VMG1.MGR_CD = MG2.MGR_CD',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0411_10
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411_10',
    NULL,
    'MGR_KIHON_VIEW VMG1, MGR_SHOKIJ MG3, KK_RENKEI RT02R',
    'RT02R.ITEM005 = VMG1.ISIN_CD AND VMG1.ITAKU_KAISHA_CD = MG3.ITAKU_KAISHA_CD AND VMG1.MGR_CD = MG3.MGR_CD AND MG3.SHOKAN_KBN = ''10''',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0411_20
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411_20',
    NULL,
    'MGR_KIHON_VIEW VMG1, MGR_SHOKIJ MG3, KK_RENKEI RT02R',
    'RT02R.ITEM005 = VMG1.ISIN_CD AND VMG1.ITAKU_KAISHA_CD = MG3.ITAKU_KAISHA_CD AND VMG1.MGR_CD = MG3.MGR_CD AND MG3.SHOKAN_KBN IN (''20'',''21'')',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R04114
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R04114',
    'VMG1.MGR_CD, VMG1.MGR_RNM, RT02.ITEM005, MG3.ITAKU_KAISHA_CD',
    'KK_RENKEI RT02, MGR_SHOKIJ MG3, MGR_KIHON_VIEW VMG1',
    'MG3.SHOKAN_KJT = RT02.ITEM025 AND MG3.SHOKAN_KBN IN (''20'',''21'')',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0411_40
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411_40',
    NULL,
    'MGR_KIHON_VIEW VMG1, MGR_SHOKIJ MG3, KK_RENKEI RT02R',
    'RT02R.ITEM005 = VMG1.ISIN_CD AND VMG1.ITAKU_KAISHA_CD = MG3.ITAKU_KAISHA_CD AND VMG1.MGR_CD = MG3.MGR_CD AND MG3.SHOKAN_KBN = ''40''',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0411_41
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411_41',
    NULL,
    'MGR_KIHON_VIEW VMG1, MGR_SHOKIJ MG3, KK_RENKEI RT02R',
    'RT02R.ITEM005 = VMG1.ISIN_CD AND VMG1.ITAKU_KAISHA_CD = MG3.ITAKU_KAISHA_CD AND VMG1.MGR_CD = MG3.MGR_CD AND MG3.SHOKAN_KBN = ''41''',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R04115
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R04115',
    'VMG1.MGR_CD, VMG1.MGR_RNM, RT02.ITEM005, MG3.ITAKU_KAISHA_CD',
    'KK_RENKEI RT02, MGR_SHOKIJ MG3, MGR_KIHON_VIEW VMG1',
    'MG3.SHOKAN_KJT = RT02.ITEM029 AND MG3.SHOKAN_KBN = ''41''',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0411_50
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0411_50',
    NULL,
    'MGR_KIHON_VIEW VMG1, MGR_SHOKIJ MG3, KK_RENKEI RT02R',
    'RT02R.ITEM005 = VMG1.ISIN_CD AND VMG1.ITAKU_KAISHA_CD = MG3.ITAKU_KAISHA_CD AND VMG1.MGR_CD = MG3.MGR_CD AND MG3.SHOKAN_KBN = ''50''',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R0811
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R0811',
    'B01W.MGR_MEISAI_NO',
    'SHINKIKIROKU B04',
    'B04.TOTSUGO_KEKKA_KBN IN (''0'',''2'',''3'') AND B04.ITAKU_KAISHA_CD = B01W.ITAKU_KAISHA_CD AND B04.ISIN_CD = B01W.ISIN_CD AND B04.HKUK_KNGK = B01W.HKUK_KNGK AND pkIpaName.getBicNoShitenCd(B04.KAI_BANKID_CD) = B01W.KAI_BANKID_CD_BIC',
    'B01W.MGR_MEISAI_NO',
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R1521
-- NOTE: Converted Oracle outer join (+) to LEFT OUTER JOIN
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R1521',
    'TRIM(RT02R.ITEM139), RT02R.ITEM007, RT02R.ITEM008, RT02R.ITEM014, RT02R.ITEM018, RT02R.ITEM019, RT02R.ITEM020, RT02R.ITEM141, RT02S.DENBUN_MEISAI_NO, MG0.MGR_TAIKEI_KBN, VMG1.MGR_RNM, MG0.KK_STAT, VMG1.ITAKU_KAISHA_CD, VMG1.PARTMGR_KBN, RT02S.KK_SAKUSEI_DT, RT02S.GYOMU_STAT_CD',
    'KK_RENKEI RT02R, MGR_KIHON VMG1, MGR_STS MG0
    LEFT OUTER JOIN KK_RENKEI RT02S ON (RT02S.JIP_DENBUN_CD = ''S1511'' 
        AND pkIpaName.getBicNoShitenCd(RT02R.SR_BIC_CD) = pkIpaName.getBicNoShitenCd(RT02S.SR_BIC_CD) 
        AND TRIM(RT02R.ITEM139) = TRIM(RT02S.ITEM139) 
        AND RT02S.ITEM005 = RT02R.ITEM005)',
    'TRIM(RT02R.ITEM139) = VMG1.MGR_CD 
        AND MG0.KK_STAT IN (''03'', ''04'') 
        AND MG0.MGR_CD = VMG1.MGR_CD 
        AND MG0.ITAKU_KAISHA_CD = VMG1.ITAKU_KAISHA_CD 
        AND MG0.MASSHO_FLG = ''0'' 
        AND RT02S.KK_SAKUSEI_DT = (SELECT MAX(K01.KK_SAKUSEI_DT) 
            FROM KK_RENKEI K01 
            WHERE K01.JIP_DENBUN_CD = ''S1511'' 
                AND RT02S.ITEM005 = K01.ITEM005 
                AND RT02S.ITEM139 = K01.ITEM139 
                AND pkIpaName.getBicNoShitenCd(RT02S.SR_BIC_CD) = pkIpaName.getBicNoShitenCd(K01.SR_BIC_CD)) 
        AND RT02S.DENBUN_STAT != ''15''',
    'RT02S.KK_SAKUSEI_DT DESC',
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

-- Record: R2811
INSERT INTO scomparing_condition (
    totsugo_no,
    select_clause,
    from_clause,
    where_clause,
    order_by_clause,
    group_by_clause,
    kousin_dt,
    kousin_id,
    sakusei_dt,
    sakusei_id
) VALUES (
    'R2811',
    'VMG1.MGR_CD, VMG1.ISIN_CD, VMG1.MGR_RNM',
    'KK_RENKEI RT02, MGR_KIHON_VIEW VMG1',
    'RT02.ITEM004 = VMG1.ISIN_CD',
    NULL,
    NULL,
    CURRENT_TIMESTAMP,
    'SYSTEM',
    CURRENT_TIMESTAMP,
    'SYSTEM'
);

