




CREATE OR REPLACE FUNCTION sfipd018k01r01 ( l_inKey_Cd text DEFAULT NULL,	--	委託会社コード		
 l_inUser_Id text DEFAULT NULL,	--	ユーザＩＤ			
 l_inChohyo_Kbn text DEFAULT NULL,	--	帳票区分			
 l_inGyomu_DT text DEFAULT NULL,	--	業務日付			
 l_inMake_Dt_From text DEFAULT NULL,	--	作成日(From)		
 l_inMake_Dt_To text DEFAULT NULL,	--	作成日(To)			
 l_inIsin_Cd_From text DEFAULT NULL,	--	ISINコード(From)	
 l_inIsin_Cd_To text DEFAULT NULL 	--	ISINコード(To)		
) RETURNS integer AS $body$
DECLARE

ora2pg_rowcount int;
--*
-- * 著作権: Copyright (c) 2005
-- * 会社名: JIP
-- *
-- * 機構銘柄口座店・ＣＩＦ付与
-- * データを作成する
-- *
-- * @author 内田　千恵子(ASK)
-- * @author 海老澤　智(ASK)
-- * @version $Revision: 1.10 $
-- 
--====================================================================*
--            変数定義
-- *====================================================================
	-- ログ出力用メッセージパラメータ
	message 					varchar(200);
	-- エラー定義           
	err 						integer := 99;
	-- 登録レコード数			
	gInsCnt						numeric(9)		:=	0;
	-- 削除レコード数			
	gDelCnt						numeric(9)		:=	0;
	g_OUT_MHAKKOTAI				RECORD;
	g_OUT_SREPORT_WK			RECORD;
	gSW							numeric(1)		:=	0;
	gSEQ_NO						numeric(10)		:=	0;
	gHAKKOTAI_COUNT				numeric(10)		:=	0;
	-- Where条件 
	g_SAKUSEI_DT_WHERE			varchar(200) := '';
	g_ISIN_CD_WHERE				varchar(100) := '';
	str_sql						varchar(400);
	CUR_1_REC					RECORD;
	tChohyoId		CONSTANT	text		:= 'IP030000141';
	-- カーソル定義 
	CUR_1 refcursor;
--====================================================================*
--   		メイン
-- *====================================================================
BEGIN
	CALL pkLog.debug('batch','','機構銘柄口座店 ＣＩＦ付与ＣＳＶファイル作成 START');
	--	入力パラメータ必須チェック	
	--	委託会社コード	
	IF	coalesce(l_inKey_Cd::text, '') = '' THEN
		message		:=	' ERROR CONSTANT INTEGER l_inKey_Cd = NULL';
		err			:=	1;
		RETURN err;
	END IF;
	--	ユーザＩＤ		
	IF	coalesce(l_inUser_Id::text, '') = '' THEN
		message		:=	' ERROR CONSTANT INTEGER l_inUser_Id = NULL';
		err			:=	1;
		RETURN err;
	END IF;
	--	帳票区分		
	IF	coalesce(l_inChohyo_Kbn::text, '') = '' THEN
		message		:=	' ERROR CONSTANT INTEGER l_inChohyo_Kbn = NULL';
		err			:=	1;
		RETURN err;
	END IF;
	--	業務日付		
	IF	coalesce(l_inGyomu_DT::text, '') = '' THEN
		message		:=	' ERROR CONSTANT INTEGER l_inGyomu_DT = NULL';
		err			:=	1;
		RETURN err;
	END IF;	
	--	機構銘柄口座店 ＣＩＦ付与ＣＳＶデータ（帳票ワーク）のデータを削除する。	
	DELETE FROM SREPORT_WK
	WHERE
		KEY_CD		=	l_inKey_Cd		AND
		USER_ID		=	l_inUser_Id		AND
		CHOHYO_KBN	=	l_inChohyo_Kbn	AND
		SAKUSEI_YMD	=	l_inGyomu_DT	AND
		CHOHYO_ID	=	tChohyoId;
	GET DIAGNOSTICS ora2pg_rowcount = ROW_COUNT;

	gDelCnt	:=	gDelCnt +  ora2pg_rowcount;
    -- ヘッダレコードを追加
    CALL pkPrint.insertHeader(l_inKey_Cd, l_inUser_Id, l_inChohyo_Kbn, l_inGyomu_DT, tChohyoId);
	gInsCnt	:=	gInsCnt + 1;
	-- 作成年月(From-To)の条件設定	
	IF (l_inMake_Dt_From IS NOT NULL AND l_inMake_Dt_From::text <> '') AND (l_inMake_Dt_To IS NOT NULL AND l_inMake_Dt_To::text <> '') THEN
		g_SAKUSEI_DT_WHERE := 'TO_CHAR(SAKUSEI_DT, ''YYYYMMDD'') >= ''' || l_inMake_Dt_From || ''' AND ' ||
							  'TO_CHAR(SAKUSEI_DT, ''YYYYMMDD'') <= ''' || l_inMake_Dt_To || ''' AND ';
	ELSIF (l_inMake_Dt_From IS NOT NULL AND l_inMake_Dt_From::text <> '') THEN
		g_SAKUSEI_DT_WHERE := 'TO_CHAR(SAKUSEI_DT, ''YYYYMMDD'') >= ''' || l_inMake_Dt_From || ''' AND ';
	ELSIF (l_inMake_Dt_To IS NOT NULL AND l_inMake_Dt_To::text <> '') THEN
		g_SAKUSEI_DT_WHERE := 'TO_CHAR(SAKUSEI_DT, ''YYYYMMDD'') <= ''' || l_inMake_Dt_To || ''' AND ';
	END IF;
	-- ISINコード(From-To)条件設定	
	IF (l_inIsin_Cd_From IS NOT NULL AND l_inIsin_Cd_From::text <> '') AND (l_inIsin_Cd_To IS NOT NULL AND l_inIsin_Cd_To::text <> '') THEN
		g_ISIN_CD_WHERE := ' AND RTRIM(ISIN_CD) >= ''' || l_inIsin_Cd_From || ''' AND RTRIM(ISIN_CD) <= ''' || l_inIsin_Cd_To || '''';
	ELSIF (l_inIsin_Cd_From IS NOT NULL AND l_inIsin_Cd_From::text <> '') THEN
		g_ISIN_CD_WHERE := ' AND RTRIM(ISIN_CD) >= ''' || l_inIsin_Cd_From || '''';
	ELSIF (l_inIsin_Cd_To IS NOT NULL AND l_inIsin_Cd_To::text <> '') THEN
		g_ISIN_CD_WHERE := ' AND RTRIM(ISIN_CD) <= ''' || l_inIsin_Cd_To || '''';
	END IF;
	str_sql :=  'SELECT * ' ||
				'FROM MGR_TEIKYOU WHERE ' ||
				g_SAKUSEI_DT_WHERE ||
				'ITAKU_KAISHA_CD = ''' || l_inKey_Cd  || '''' ||
				g_ISIN_CD_WHERE;
	OPEN CUR_1 FOR EXECUTE str_sql;
	LOOP 	
		FETCH CUR_1 INTO CUR_1_REC;
		EXIT WHEN NOT FOUND;/* apply on CUR_1 */
		IF	gSW	=	0	THEN
			gSW	:=	1;
		END IF;
		--	９０Ｂ体系を判断	
		IF	'90B'	!=	substr(CUR_1_REC.ISIN_CD,3,3)	THEN
			SELECT
				COUNT(*)
			INTO
				gHAKKOTAI_COUNT
			FROM
				MHAKKOTAI
			WHERE
				ITAKU_KAISHA_CD	=	l_inKey_Cd	AND
				KK_HAKKO_CD		=	CUR_1_REC.KK_HAKKO_CD;
			IF gHAKKOTAI_COUNT::integer != 0 THEN
				--	発行体マスタより、口座店コード、口座店ＣＩＦコード の取得	
				SELECT
					KOZA_TEN_CD,
					KOZA_TEN_CIFCD
				INTO STRICT
					g_OUT_MHAKKOTAI.KOZA_TEN_CD,
					g_OUT_MHAKKOTAI.KOZA_TEN_CIFCD
				FROM
					MHAKKOTAI
				WHERE
					ITAKU_KAISHA_CD	=	l_inKey_Cd	AND
					KK_HAKKO_CD		=	CUR_1_REC.KK_HAKKO_CD  LIMIT 1;
			ELSE
				g_OUT_MHAKKOTAI.KOZA_TEN_CD := NULL;
				g_OUT_MHAKKOTAI.KOZA_TEN_CIFCD := NULL;
			END IF;
		ELSE
			SELECT
				COUNT(*)
			INTO
				gHAKKOTAI_COUNT
			FROM
				MHAKKOTAI
			WHERE
				ITAKU_KAISHA_CD	=	l_inKey_Cd	AND
				KK_HAKKOSHA_RNM	=	CUR_1_REC.MGR_RNM_HAKKOSHA_RNM;
			IF gHAKKOTAI_COUNT::integer != 0 THEN
				--	発行体マスタより、口座店コード、口座店ＣＩＦコード の取得	
				SELECT
					KOZA_TEN_CD,
					KOZA_TEN_CIFCD
				INTO STRICT
					g_OUT_MHAKKOTAI.KOZA_TEN_CD,
					g_OUT_MHAKKOTAI.KOZA_TEN_CIFCD
				FROM
					MHAKKOTAI
				WHERE
					ITAKU_KAISHA_CD	=	l_inKey_Cd	AND
					KK_HAKKOSHA_RNM	=	CUR_1_REC.MGR_RNM_HAKKOSHA_RNM  LIMIT 1;
			ELSE
				g_OUT_MHAKKOTAI.KOZA_TEN_CD := NULL;
				g_OUT_MHAKKOTAI.KOZA_TEN_CIFCD := NULL;
			END IF;
		END IF;
		--	出力項目へセットする	
		g_OUT_SREPORT_WK.KEY_CD			:=	l_inKey_Cd;
		g_OUT_SREPORT_WK.USER_ID		:=	l_inUser_Id;
		g_OUT_SREPORT_WK.CHOHYO_KBN		:=	l_inChohyo_Kbn;
		g_OUT_SREPORT_WK.SAKUSEI_YMD	:=	l_inGyomu_DT;
		g_OUT_SREPORT_WK.CHOHYO_ID		:=	tChohyoId;
		g_OUT_SREPORT_WK.SEQ_NO			:=	gSEQ_NO	+	1;
		g_OUT_SREPORT_WK.HEADER_FLG		:=	1;
		g_OUT_SREPORT_WK.ITEM001	:= RTRIM(CUR_1_REC.ITAKU_KAISHA_CD);
		g_OUT_SREPORT_WK.ITEM002	:= RTRIM(CUR_1_REC.ISIN_CD);
		g_OUT_SREPORT_WK.ITEM003	:= RTRIM(CUR_1_REC.MGR_NM);
		g_OUT_SREPORT_WK.ITEM004	:= RTRIM(CUR_1_REC.MGR_RNM_HAKKOSHA_RNM);
		g_OUT_SREPORT_WK.ITEM005	:= RTRIM(CUR_1_REC.MGR_RNM_KAIGO_ETC);
		g_OUT_SREPORT_WK.ITEM006	:= RTRIM(CUR_1_REC.MGR_RNM_BOSHU_KBN);
		g_OUT_SREPORT_WK.ITEM007	:= RTRIM(CUR_1_REC.FIXDISPLAY);
		g_OUT_SREPORT_WK.ITEM008	:= RTRIM(CUR_1_REC.HOSHO_KBN);
		g_OUT_SREPORT_WK.ITEM009	:= RTRIM(CUR_1_REC.TANPO_KBN);
		g_OUT_SREPORT_WK.ITEM010	:= RTRIM(CUR_1_REC.PARTHAKKO_UMU_FLG);
		g_OUT_SREPORT_WK.ITEM011	:= RTRIM(CUR_1_REC.GODOHAKKO_FLG);
		g_OUT_SREPORT_WK.ITEM012	:= RTRIM(CUR_1_REC.RETSUTOKU_UMU_FLG);
		g_OUT_SREPORT_WK.ITEM013	:= RTRIM(CUR_1_REC.SKNNZISNTOKU_UMU_FLG);
		g_OUT_SREPORT_WK.ITEM014	:= RTRIM(CUR_1_REC.SAIKEN_SHURUI);
		g_OUT_SREPORT_WK.ITEM015	:= RTRIM(CUR_1_REC.KK_HAKKO_CD);
		g_OUT_SREPORT_WK.ITEM016	:= RTRIM(CUR_1_REC.BOSHU_ST_YMD);
		g_OUT_SREPORT_WK.ITEM017	:= RTRIM(CUR_1_REC.HRKM_YMD);
		g_OUT_SREPORT_WK.ITEM018	:= CUR_1_REC.KAKUSHASAI_KNGK;
		g_OUT_SREPORT_WK.ITEM019	:= RTRIM(CUR_1_REC.UCHIKIRI_HAKKO_FLG);
		g_OUT_SREPORT_WK.ITEM020	:= CUR_1_REC.SHASAI_TOTAL;
		g_OUT_SREPORT_WK.ITEM021	:= RTRIM(CUR_1_REC.HAKKO_TSUKA_CD);
		g_OUT_SREPORT_WK.ITEM022	:= RTRIM(CUR_1_REC.HAKKODAIRI_CD);
		g_OUT_SREPORT_WK.ITEM023	:= RTRIM(CUR_1_REC.SHRDAIRI_CD);
		g_OUT_SREPORT_WK.ITEM024	:= RTRIM(CUR_1_REC.SKN_KESSAI_CD);
		g_OUT_SREPORT_WK.ITEM025	:= RTRIM(CUR_1_REC.KK_KANYO_FLG);
		g_OUT_SREPORT_WK.ITEM026	:= RTRIM(CUR_1_REC.KOBETSU_SHONIN_SAIYO_FLG);
		g_OUT_SREPORT_WK.ITEM027	:= RTRIM(CUR_1_REC.KYUJITSU_KBN);
		g_OUT_SREPORT_WK.ITEM028	:= RTRIM(CUR_1_REC.LD_FLG);
		g_OUT_SREPORT_WK.ITEM029	:= RTRIM(CUR_1_REC.NY_FLG);
		g_OUT_SREPORT_WK.ITEM030	:= RTRIM(CUR_1_REC.ETCKAIGAI_FLG);
		g_OUT_SREPORT_WK.ITEM031	:= RTRIM(CUR_1_REC.ETCKAIGAI_RBR_YMD);
		g_OUT_SREPORT_WK.ITEM032	:= RTRIM(CUR_1_REC.RITSUKE_WARIBIKI_KBN);
		g_OUT_SREPORT_WK.ITEM033	:= RTRIM(CUR_1_REC.RBR_TSUKA_CD);
		g_OUT_SREPORT_WK.ITEM034	:= RTRIM(CUR_1_REC.RBR_KJT_MD1);
		g_OUT_SREPORT_WK.ITEM035	:= RTRIM(CUR_1_REC.RBR_KJT_MD2);
		g_OUT_SREPORT_WK.ITEM036	:= RTRIM(CUR_1_REC.RBR_KJT_MD3);
		g_OUT_SREPORT_WK.ITEM037	:= RTRIM(CUR_1_REC.RBR_KJT_MD4);
		g_OUT_SREPORT_WK.ITEM038	:= RTRIM(CUR_1_REC.RBR_KJT_MD5);
		g_OUT_SREPORT_WK.ITEM039	:= RTRIM(CUR_1_REC.RBR_KJT_MD6);
		g_OUT_SREPORT_WK.ITEM040	:= RTRIM(CUR_1_REC.RBR_KJT_MD7);
		g_OUT_SREPORT_WK.ITEM041	:= RTRIM(CUR_1_REC.RBR_KJT_MD8);
		g_OUT_SREPORT_WK.ITEM042	:= RTRIM(CUR_1_REC.RBR_KJT_MD9);
		g_OUT_SREPORT_WK.ITEM043	:= RTRIM(CUR_1_REC.RBR_KJT_MD10);
		g_OUT_SREPORT_WK.ITEM044	:= RTRIM(CUR_1_REC.RBR_KJT_MD11);
		g_OUT_SREPORT_WK.ITEM045	:= RTRIM(CUR_1_REC.RBR_KJT_MD12);
		g_OUT_SREPORT_WK.ITEM046	:= RTRIM(CUR_1_REC.ST_RBR_KJT);
		g_OUT_SREPORT_WK.ITEM047	:= RTRIM(CUR_1_REC.LAST_RBR_FLG);
		g_OUT_SREPORT_WK.ITEM048	:= RTRIM(CUR_1_REC.THIS_RBR_KJT);
		g_OUT_SREPORT_WK.ITEM049	:= CUR_1_REC.THIS_RIRITSU;
		g_OUT_SREPORT_WK.ITEM050	:= CUR_1_REC.THIS_TSUKARISHI_KNGK;
		g_OUT_SREPORT_WK.ITEM051	:= RTRIM(CUR_1_REC.NEXT_RBR_KJT);
		g_OUT_SREPORT_WK.ITEM052	:= CUR_1_REC.NEXT_RIRITSU;
		g_OUT_SREPORT_WK.ITEM053	:= CUR_1_REC.NEXT_TSUKARISHI_KNGK;
		g_OUT_SREPORT_WK.ITEM054	:= RTRIM(CUR_1_REC.LAST_SHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM055	:= CUR_1_REC.LAST_RIRITSU;
		g_OUT_SREPORT_WK.ITEM056	:= CUR_1_REC.LAST_TSUKARISHI_KNGK;
		g_OUT_SREPORT_WK.ITEM057	:= RTRIM(CUR_1_REC.SHOKAN_TSUKA_CD);
		g_OUT_SREPORT_WK.ITEM058	:= CUR_1_REC.KAWASE_RATE;
		g_OUT_SREPORT_WK.ITEM059	:= CUR_1_REC.SHOKAN_PREMIUM;
		g_OUT_SREPORT_WK.ITEM060	:= RTRIM(CUR_1_REC.FULLSHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM061	:= RTRIM(CUR_1_REC.TEKIYO_END_YMD);
		g_OUT_SREPORT_WK.ITEM062	:= RTRIM(CUR_1_REC.NEWISIN_CD);
		g_OUT_SREPORT_WK.ITEM063	:= RTRIM(CUR_1_REC.CALLALL_UMU_FLG);
		g_OUT_SREPORT_WK.ITEM064	:= RTRIM(CUR_1_REC.CALLALL_USE_FLG);
		g_OUT_SREPORT_WK.ITEM065	:= RTRIM(CUR_1_REC.CALLALL_KURIAGE_SHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM066	:= CUR_1_REC.CALLALL_PLEMIUM_KNGK;
		g_OUT_SREPORT_WK.ITEM067	:= CUR_1_REC.CALLALL_TSUKA_RISHI_KNGK;
		g_OUT_SREPORT_WK.ITEM068	:= RTRIM(CUR_1_REC.TEIJI_SHOKAN_UMU_FLG);
		g_OUT_SREPORT_WK.ITEM069	:= RTRIM(CUR_1_REC.ST_TEIJISHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM070	:= RTRIM(CUR_1_REC.TEIJI_SHOKAN_TSUTI_KBN);
		g_OUT_SREPORT_WK.ITEM071	:= RTRIM(CUR_1_REC.BEF_TEIJI_SHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM072	:= CUR_1_REC.BEF_TEIJI_SHOKAN_KNGK;
		g_OUT_SREPORT_WK.ITEM073	:= CUR_1_REC.BEF_FACTOR;
		g_OUT_SREPORT_WK.ITEM074	:= RTRIM(CUR_1_REC.THIS_TEIJI_SHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM075	:= CUR_1_REC.THIS_TEIJI_SHOKAN_KNGK;
		g_OUT_SREPORT_WK.ITEM076	:= CUR_1_REC.THIS_FACTOR;
		g_OUT_SREPORT_WK.ITEM077	:= RTRIM(CUR_1_REC.NEXT_YOTEI_TEIJI_SHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM078	:= CUR_1_REC.NEXT_YOTEI_TEIJI_SHOKAN_KNGK;
		g_OUT_SREPORT_WK.ITEM079	:= CUR_1_REC.NEXT_YOTEI_FACTOR;
		g_OUT_SREPORT_WK.ITEM080	:= RTRIM(CUR_1_REC.CALLITIBU_UMU_FLG);
		g_OUT_SREPORT_WK.ITEM081	:= RTRIM(CUR_1_REC.CALLITIBU_USE_FLG);
		g_OUT_SREPORT_WK.ITEM082	:= RTRIM(CUR_1_REC.CALLITIBU_KURIAGE_SHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM083	:= CUR_1_REC.CALLITIBU_PLEMIUM_KNGK;
		g_OUT_SREPORT_WK.ITEM084	:= CUR_1_REC.CALLITIBU_KURIAGE_SHOKAN_KNGK;
		g_OUT_SREPORT_WK.ITEM085	:= CUR_1_REC.CALLITIBU_FACTOR;
		g_OUT_SREPORT_WK.ITEM086	:= CUR_1_REC.CALLITIBU_TSUKA_RISHI_KNGK;
		g_OUT_SREPORT_WK.ITEM087	:= RTRIM(CUR_1_REC.PUTUMU_FLG);
		g_OUT_SREPORT_WK.ITEM088	:= RTRIM(CUR_1_REC.PUTUSE_FLG);
		g_OUT_SREPORT_WK.ITEM089	:= RTRIM(CUR_1_REC.PUT_USE_ST_YMD);
		g_OUT_SREPORT_WK.ITEM090	:= RTRIM(CUR_1_REC.PUT_USE_ED_YMD);
		g_OUT_SREPORT_WK.ITEM091	:= RTRIM(CUR_1_REC.PUT_KURIAGE_SHOKAN_KJT);
		g_OUT_SREPORT_WK.ITEM092	:= CUR_1_REC.PUT_PLEMIUM_KNGK;
		g_OUT_SREPORT_WK.ITEM093	:= RTRIM(CUR_1_REC.TOKUREI_SHASAI_FLG);
		g_OUT_SREPORT_WK.ITEM094	:= RTRIM(CUR_1_REC.IKKATSUIKO_FLG);
		g_OUT_SREPORT_WK.ITEM095	:= RTRIM(CUR_1_REC.TKTI_KOZA_CD);
		g_OUT_SREPORT_WK.ITEM096	:= RTRIM(CUR_1_REC.GENISIN_CD);
		g_OUT_SREPORT_WK.ITEM097	:= RTRIM(CUR_1_REC.PARTMGR_KBN);
		g_OUT_SREPORT_WK.ITEM098	:= RTRIM(g_OUT_MHAKKOTAI.KOZA_TEN_CD);
		g_OUT_SREPORT_WK.ITEM099	:= RTRIM(g_OUT_MHAKKOTAI.KOZA_TEN_CIFCD);
		--	帳票_WKへ登録する	
		INSERT INTO SREPORT_WK(
			KEY_CD
			,USER_ID
			,CHOHYO_KBN
			,SAKUSEI_YMD
			,CHOHYO_ID
			,SEQ_NO
			,HEADER_FLG
			,ITEM001
			,ITEM002
			,ITEM003
			,ITEM004
			,ITEM005
			,ITEM006
			,ITEM007
			,ITEM008
			,ITEM009
			,ITEM010
			,ITEM011
			,ITEM012
			,ITEM013
			,ITEM014
			,ITEM015
			,ITEM016
			,ITEM017
			,ITEM018
			,ITEM019
			,ITEM020
			,ITEM021
			,ITEM022
			,ITEM023
			,ITEM024
			,ITEM025
			,ITEM026
			,ITEM027
			,ITEM028
			,ITEM029
			,ITEM030
			,ITEM031
			,ITEM032
			,ITEM033
			,ITEM034
			,ITEM035
			,ITEM036
			,ITEM037
			,ITEM038
			,ITEM039
			,ITEM040
			,ITEM041
			,ITEM042
			,ITEM043
			,ITEM044
			,ITEM045
			,ITEM046
			,ITEM047
			,ITEM048
			,ITEM049
			,ITEM050
			,ITEM051
			,ITEM052
			,ITEM053
			,ITEM054
			,ITEM055
			,ITEM056
			,ITEM057
			,ITEM058
			,ITEM059
			,ITEM060
			,ITEM061
			,ITEM062
			,ITEM063
			,ITEM064
			,ITEM065
			,ITEM066
			,ITEM067
			,ITEM068
			,ITEM069
			,ITEM070
			,ITEM071
			,ITEM072
			,ITEM073
			,ITEM074
			,ITEM075
			,ITEM076
			,ITEM077
			,ITEM078
			,ITEM079
			,ITEM080
			,ITEM081
			,ITEM082
			,ITEM083
			,ITEM084
			,ITEM085
			,ITEM086
			,ITEM087
			,ITEM088
			,ITEM089
			,ITEM090
			,ITEM091
			,ITEM092
			,ITEM093
			,ITEM094
			,ITEM095
			,ITEM096
			,ITEM097
			,ITEM098
			,ITEM099
			,SAKUSEI_ID
		) VALUES (
			g_OUT_SREPORT_WK.KEY_CD,
			g_OUT_SREPORT_WK.USER_ID,
			g_OUT_SREPORT_WK.CHOHYO_KBN,
			g_OUT_SREPORT_WK.SAKUSEI_YMD,
			g_OUT_SREPORT_WK.CHOHYO_ID,
			g_OUT_SREPORT_WK.SEQ_NO,
			g_OUT_SREPORT_WK.HEADER_FLG,
			g_OUT_SREPORT_WK.ITEM001,
			g_OUT_SREPORT_WK.ITEM002,
			g_OUT_SREPORT_WK.ITEM003,
			g_OUT_SREPORT_WK.ITEM004,
			g_OUT_SREPORT_WK.ITEM005,
			g_OUT_SREPORT_WK.ITEM006,
			g_OUT_SREPORT_WK.ITEM007,
			g_OUT_SREPORT_WK.ITEM008,
			g_OUT_SREPORT_WK.ITEM009,
			g_OUT_SREPORT_WK.ITEM010,
			g_OUT_SREPORT_WK.ITEM011,
			g_OUT_SREPORT_WK.ITEM012,
			g_OUT_SREPORT_WK.ITEM013,
			g_OUT_SREPORT_WK.ITEM014,
			g_OUT_SREPORT_WK.ITEM015,
			g_OUT_SREPORT_WK.ITEM016,
			g_OUT_SREPORT_WK.ITEM017,
			g_OUT_SREPORT_WK.ITEM018,
			g_OUT_SREPORT_WK.ITEM019,
			g_OUT_SREPORT_WK.ITEM020,
			g_OUT_SREPORT_WK.ITEM021,
			g_OUT_SREPORT_WK.ITEM022,
			g_OUT_SREPORT_WK.ITEM023,
			g_OUT_SREPORT_WK.ITEM024,
			g_OUT_SREPORT_WK.ITEM025,
			g_OUT_SREPORT_WK.ITEM026,
			g_OUT_SREPORT_WK.ITEM027,
			g_OUT_SREPORT_WK.ITEM028,
			g_OUT_SREPORT_WK.ITEM029,
			g_OUT_SREPORT_WK.ITEM030,
			g_OUT_SREPORT_WK.ITEM031,
			g_OUT_SREPORT_WK.ITEM032,
			g_OUT_SREPORT_WK.ITEM033,
			g_OUT_SREPORT_WK.ITEM034,
			g_OUT_SREPORT_WK.ITEM035,
			g_OUT_SREPORT_WK.ITEM036,
			g_OUT_SREPORT_WK.ITEM037,
			g_OUT_SREPORT_WK.ITEM038,
			g_OUT_SREPORT_WK.ITEM039,
			g_OUT_SREPORT_WK.ITEM040,
			g_OUT_SREPORT_WK.ITEM041,
			g_OUT_SREPORT_WK.ITEM042,
			g_OUT_SREPORT_WK.ITEM043,
			g_OUT_SREPORT_WK.ITEM044,
			g_OUT_SREPORT_WK.ITEM045,
			g_OUT_SREPORT_WK.ITEM046,
			g_OUT_SREPORT_WK.ITEM047,
			g_OUT_SREPORT_WK.ITEM048,
			g_OUT_SREPORT_WK.ITEM049,
			g_OUT_SREPORT_WK.ITEM050,
			g_OUT_SREPORT_WK.ITEM051,
			g_OUT_SREPORT_WK.ITEM052,
			g_OUT_SREPORT_WK.ITEM053,
			g_OUT_SREPORT_WK.ITEM054,
			g_OUT_SREPORT_WK.ITEM055,
			g_OUT_SREPORT_WK.ITEM056,
			g_OUT_SREPORT_WK.ITEM057,
			g_OUT_SREPORT_WK.ITEM058,
			g_OUT_SREPORT_WK.ITEM059,
			g_OUT_SREPORT_WK.ITEM060,
			g_OUT_SREPORT_WK.ITEM061,
			g_OUT_SREPORT_WK.ITEM062,
			g_OUT_SREPORT_WK.ITEM063,
			g_OUT_SREPORT_WK.ITEM064,
			g_OUT_SREPORT_WK.ITEM065,
			g_OUT_SREPORT_WK.ITEM066,
			g_OUT_SREPORT_WK.ITEM067,
			g_OUT_SREPORT_WK.ITEM068,
			g_OUT_SREPORT_WK.ITEM069,
			g_OUT_SREPORT_WK.ITEM070,
			g_OUT_SREPORT_WK.ITEM071,
			g_OUT_SREPORT_WK.ITEM072,
			g_OUT_SREPORT_WK.ITEM073,
			g_OUT_SREPORT_WK.ITEM074,
			g_OUT_SREPORT_WK.ITEM075,
			g_OUT_SREPORT_WK.ITEM076,
			g_OUT_SREPORT_WK.ITEM077,
			g_OUT_SREPORT_WK.ITEM078,
			g_OUT_SREPORT_WK.ITEM079,
			g_OUT_SREPORT_WK.ITEM080,
			g_OUT_SREPORT_WK.ITEM081,
			g_OUT_SREPORT_WK.ITEM082,
			g_OUT_SREPORT_WK.ITEM083,
			g_OUT_SREPORT_WK.ITEM084,
			g_OUT_SREPORT_WK.ITEM085,
			g_OUT_SREPORT_WK.ITEM086,
			g_OUT_SREPORT_WK.ITEM087,
			g_OUT_SREPORT_WK.ITEM088,
			g_OUT_SREPORT_WK.ITEM089,
			g_OUT_SREPORT_WK.ITEM090,
			g_OUT_SREPORT_WK.ITEM091,
			g_OUT_SREPORT_WK.ITEM092,
			g_OUT_SREPORT_WK.ITEM093,
			g_OUT_SREPORT_WK.ITEM094,
			g_OUT_SREPORT_WK.ITEM095,
			g_OUT_SREPORT_WK.ITEM096,
			g_OUT_SREPORT_WK.ITEM097,
			g_OUT_SREPORT_WK.ITEM098,
			g_OUT_SREPORT_WK.ITEM099,
			l_inUser_Id
		);
		gSEQ_NO	:=	gSEQ_NO + 1;
		gInsCnt	:=	gInsCnt + 1;
	END LOOP;
	CLOSE CUR_1;
--	IF gInsCnt > 1 THEN
	IF gInsCnt::integer = 1 THEN
		INSERT INTO SREPORT_WK(
			KEY_CD,
			USER_ID,
			CHOHYO_KBN,
			SAKUSEI_YMD,
			CHOHYO_ID,
			SEQ_NO,
			HEADER_FLG,
			ITEM001,
			SAKUSEI_ID
		) VALUES (
			l_inKey_Cd,
			l_inUser_Id,
			l_inChohyo_Kbn,
			l_inGyomu_DT,
			tChohyoId,
			1,
			1,
			'対象データなし',
			l_inUser_Id
		);
		gInsCnt	:=	gInsCnt + 1;
	END IF;
	-- 件数出力ログ 
	CALL pkLog.debug('batch','','削除件数 = '||pkcharacter.numeric_to_char(gDelCnt));
	CALL pkLog.debug('batch','','登録件数 = '||pkcharacter.numeric_to_char(gInsCnt));
	CALL pkLog.debug('batch','','機構銘柄口座店 ＣＩＦ付与ＣＳＶファイル作成 END');
	RETURN 0;
--====================================================================*
--    異常終了 出口
-- *====================================================================
EXCEPTION WHEN OTHERS THEN
	CALL pkLog.error('ECM701','',SQLERRM);
	CALL pkLog.error('ECM701','','Call stack not available in PostgreSQL');
	message := 'TEMP 機構銘柄口座店 ＣＩＦ付与ＣＳＶファイル作成エラー SQLSTATE= ' ||
	SQLSTATE || ' ' || SUBSTR(SQLERRM, 1, 100);
	CALL pkLog.fatal('ECM701','SFIPD018K01R01',message);
	CALL pkLog.error('ECM701','','TEMP 機構銘柄口座店 ＣＩＦ付与ＣＳＶファイル作成エラー SQLSTATE= ' || SQLSTATE);
	RETURN 99;
END;
$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON FUNCTION sfipd018k01r01 ( l_inKey_Cd text DEFAULT NULL, l_inUser_Id text DEFAULT NULL, l_inChohyo_Kbn text DEFAULT NULL, l_inGyomu_DT text DEFAULT NULL, l_inMake_Dt_From text DEFAULT NULL, l_inMake_Dt_To text DEFAULT NULL, l_inIsin_Cd_From text DEFAULT NULL, l_inIsin_Cd_To text DEFAULT NULL  ) FROM PUBLIC;